name: Trigger API Gateway CI/CD

on:
  push:
    paths:
      - 'api-gateway-sandbox.yaml'

jobs:
  trigger-api:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch Event
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          https://api.github.com/repos/SamyakTechLabs/sangh-management-api-gateway/dispatches \
          -d '{"event_type": "api-gateway-update"}' \
          -v
